import pathlib
lines = []
lines.append("# Plan: Dashboard Cockpit")
lines.append("")
lines.append("## Status")
lines.append("- [x] Draft")
lines.append("- [x] Review")
lines.append("- [x] Approved")
lines.append("- [ ] In Progress")
lines.append("- [ ] Complete")
lines.append("")
lines.append("## Design System")
lines.append("Glassmorphism + bento boxes + modern startup UX")
lines.append("See notes/design.md for full design tokens and CSS snippets")
lines.append("")
lines.append("## Agent Roster")
lines.append("")
lines.append("| Role | Who | Responsibility |")
lines.append("|---|---|---|")
lines.append("| Orchestrator | Me | Coordinate phases, write spec/plan, spawn agents, review, merge |")
lines.append("| Designer | Grok + Stitch MCP | Generate glassmorphism+bento UI design via Google Stitch MCP |")
lines.append("| Subagent A | Grok | Repair homepage Try It section - wire to real API endpoints |")
lines.append("| Subagent B | Grok | Redesign /tournament/new with anchor picker, profile picker |")
lines.append("| Subagent C | Grok | Redesign /tournament/[id] poker board with swim lanes + IdeaCards |")
lines.append("| Subagent D | Grok | Build BudgetMeter + Diagnosis components |")
lines.append("| Subagent E | Grok | Build ReentryButton + polish memo page with RealitySpikeCard |")
lines.append("| Reviewer | Me | Review all commits after subagents, create PRs for issues |")
lines.append("| Fix Agent | Grok | Fix issues identified in review, PR -> fix -> re-review -> merge |")
lines.append("")
lines.append("## Execution Phases")
lines.append("")
lines.append("### Phase 0: Setup (Done)")
lines.append("- Feature directory: agentdocs/features/dashboard-cockpit/")
lines.append("- spec.md, plan.md, tasks/01-05, notes/design.md created")
lines.append("- API :8000 and frontend :3000 running")
lines.append("")
lines.append("### Phase 1: Design (Next - Grok + Google Stitch MCP)")
lines.append("- Prompt Grok with Stitch MCP to generate glassmorphism startup UI")
lines.append("- Apply glassmorphism tokens (backdrop-filter, rgba borders, glow) to frontend")
lines.append("- Convert card layouts to bento box grids")
lines.append("")
lines.append("### Phase 2: Implementation (Subagents A-E in parallel)")
lines.append("")
lines.append("#### A: Homepage -> /harvest + /generate (FR-1)")
lines.append("#### B: Tournament seed form (FR-3)")
lines.append("#### C: Poker board swim lanes + IdeaCards (FR-4, FR-5)")
lines.append("#### D: BudgetMeter + Diagnosis (FR-6, FR-9)")
lines.append("#### E: ReentryButton + memo RealitySpikeCard (FR-7, FR-10)")
lines.append("")
lines.append("### Phase 3: Review")
lines.append("- Review each commit against spec")
lines.append("- Issues -> PR -> Grok fixes -> re-review -> merge")
lines.append("")
lines.append("### Phase 4: Verify")
lines.append("- Full pipeline smoke test: invoice reconciliation end-to-end")
lines.append("")
lines.append("## Task Mapping")
lines.append("")
lines.append("| Task | File | Agent | Reqs |")
lines.append("|---|---|---|---|")
lines.append("| Homepage | tasks/01-homepage-try-it.md | A | FR-1 |")
lines.append("| Seed Form | tasks/02-tournament-seed-form.md | B | FR-3 |")
lines.append("| Poker Board | tasks/03-poker-board.md | C | FR-4, FR-5 |")
lines.append("| BudgetMeter | tasks/04-budget-meter-diagnosis.md | D | FR-6, FR-9 |")
lines.append("| Reentry | tasks/05-reentry-memo.md | E | FR-7, FR-10 |")
lines.append("| Design | notes/design.md | Designer | All NFRs |")
pathlib.Path("C:/experiments/evidentia/main/agentdocs/features/dashboard-cockpit/plan.md").write_text("\n".join(lines), encoding="utf-8")
print("Plan updated")
